[tasks.format]
description = "Run the cargo rustfmt plugin"
install_crate = "rustfmt"
command = "cargo"
args = ["fmt"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build", "--release"]
dependencies = ["clean"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["clean"]

[tasks.pre-commit]
dependencies = ["format", "build", "test"]

[tasks.link-hooks]
command = "ln"
args = ["-s", "pre-commit.sh", ".git/hooks/pre-commit"]