[tasks.docs]
command = "cargo"
args = ["doc"]

[tasks.enable-hooks]
description = "Enables or updates Git hooks"
command = "ln"
args = ["-sf", "pre-commit.sh", ".git/hooks/pre-commit"]

[tasks.disable-hooks]
description = "Disables Git hooks"
command = "rm"
args = [".git/hooks/pre-commit"]